// Code generated by goctl. DO NOT EDIT.
package types

type AddReply struct {
	Sum int `json:"sum"`
}

type AddReq struct {
	A int `path:"a"` // 这种方式，请求时 a 的值为 url 路径的一部分，而不是参数的一部分，调用示例：/add/1/3，这里 1 为 a 的值，3 为 b 的值，可通过 internal/handler/routes.go 的实现看出来
	B int `path:"b"`
}
