// Code generated by goctl. DO NOT EDIT.
// Source: authentication.proto

package server

import (
	"context"

	"authentication/internal/logic"
	"authentication/internal/svc"
	"authentication/protoc/auth"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) Authenticate(ctx context.Context, in *auth.AuthReq) (*auth.AuthResp, error) {
	l := logic.NewAuthenticateLogic(ctx, s.svcCtx)
	return l.Authenticate(in)
}
